version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      day: "monday"
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: "tuesday"
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
