image:
  file: .gp/Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
  - port: 9200
    onOpen: ignore

tasks:
  - init: |
      ./.gp/init
    command: |
      ./.gp/setup_db
      bundle exec rails server

github:
  prebuilds:
    pullRequestsFromForks: true
