image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
  - port: 9200
    onOpen: ignore

tasks:
  - init: |
      bundle install --jobs=4 --retry=3 --path vendor/bundle
    command: |
      docker-compose up -d postgresql elasticsearch
      gp await-port 5432
      bundle exec rake db:create
      bundle exec rake db:schema:load
      RAILS_ENV=test bundle exec rake db:schema:load
      bundle exec rails server

github:
  prebuilds:
    pullRequestsFromForks: true
