ports:
  - port: 5432
    onOpen: ignore
  - port: 9200
    onOpen: ignore

tasks:
  - init: touch aws-cli.env
    command: docker-compose up elasticsearch
  - init: touch aws-cli.env
    command: docker-compose up postgresql

image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    pullRequestsFromForks: true