image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
  - port: 9200
    onOpen: ignore

tasks:
  - init: |
      docker-compose up -d postgresql elasticsearch
      bundle install --jobs=4 --retry=3
      rake db:create
      rake db:schema:load
      RAILS_ENV=test rake db:schema:load
    command: rails server

github:
  prebuilds:
    pullRequestsFromForks: true