version: '2'
services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - postgis
    environment:
      DATABASE_HOST: postgis
      DATABASE_PORT: 5432
      DATABASE_USER: safecast
      DATABASE_PASSWORD: safecast
      DATABASE_NAME: safecast

  postgis:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: safecast
      POSTGRES_PASSWORD: safecast
      POSTGRES_DB: safecast
