 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/device_story_comments", type: :request do
  # DeviceStoryComment. As you add validations to DeviceStoryComment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DeviceStoryComment.create! valid_attributes
      get device_story_comments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      device_story_comment = DeviceStoryComment.create! valid_attributes
      get device_story_comment_url(device_story_comment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_device_story_comment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      device_story_comment = DeviceStoryComment.create! valid_attributes
      get edit_device_story_comment_url(device_story_comment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DeviceStoryComment" do
        expect {
          post device_story_comments_url, params: { device_story_comment: valid_attributes }
        }.to change(DeviceStoryComment, :count).by(1)
      end

      it "redirects to the created device_story_comment" do
        post device_story_comments_url, params: { device_story_comment: valid_attributes }
        expect(response).to redirect_to(device_story_comment_url(DeviceStoryComment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DeviceStoryComment" do
        expect {
          post device_story_comments_url, params: { device_story_comment: invalid_attributes }
        }.to change(DeviceStoryComment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post device_story_comments_url, params: { device_story_comment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested device_story_comment" do
        device_story_comment = DeviceStoryComment.create! valid_attributes
        patch device_story_comment_url(device_story_comment), params: { device_story_comment: new_attributes }
        device_story_comment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the device_story_comment" do
        device_story_comment = DeviceStoryComment.create! valid_attributes
        patch device_story_comment_url(device_story_comment), params: { device_story_comment: new_attributes }
        device_story_comment.reload
        expect(response).to redirect_to(device_story_comment_url(device_story_comment))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        device_story_comment = DeviceStoryComment.create! valid_attributes
        patch device_story_comment_url(device_story_comment), params: { device_story_comment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested device_story_comment" do
      device_story_comment = DeviceStoryComment.create! valid_attributes
      expect {
        delete device_story_comment_url(device_story_comment)
      }.to change(DeviceStoryComment, :count).by(-1)
    end

    it "redirects to the device_story_comments list" do
      device_story_comment = DeviceStoryComment.create! valid_attributes
      delete device_story_comment_url(device_story_comment)
      expect(response).to redirect_to(device_story_comments_url)
    end
  end
end
