#!/usr/bin/env bash

# Performs a full, unfiltered dump of the measurements table.

set -euo pipefail

source cron_env.sh

cd ../public/system

psql -f "${CRON_DIR}/dump_measurements.sql"

tar -czf measurements-out.tar.gz measurements-out.csv
mv measurements-out.csv measurements.csv
mv measurements-out.tar.gz measurements.tar.gz

# Now this is available as https://api.safecast.org/system/measurements.tar.gz
