#!/usr/bin/env bash

# Add a new City:
# 1. Add the city name to the city_names_array at line 13 of the calculate_radiation_index file
# 2. Add a query with the coordinates to the radiation_index_export.sql file. The file must be named [cityname]_export.csv

set -euo pipefail

source cron_env.sh

cd ../public/system

psql -f "${CRON_DIR}/radiation_index_export.sql"
ruby "${CRON_DIR}/calculate_radiation_index"
