#!/bin/sh
# Add a new City:
# 1. Add the city name to the city_names_array at line 13 of the calculate_radiation_index file
# 2. Add a query with the coordinates to the radiation_index_export.sql file. The file must be named [cityname]_export.csv

[[ -f /opt/elasticbeanstalk/support/envvars ]] && source /opt/elasticbeanstalk/support/envvars

export PGHOST="${DATABASE_HOST}"
export PGPORT=5432
export PGDATABASE=safecast
export PGUSER=safecast
export PGPASSWORD="${DATABASE_PASSWORD}"

cd "$(dirname "$0")"
SCRIPT_DIR="$(pwd)"

cd "${SHARED_SYSTEM_PATH}"

psql -f "${SCRIPT_DIR}/radiation_index_export.sql"
ruby "${SCRIPT_DIR}/calculate_radiation_index"
