#!/usr/bin/env ruby
# frozen_string_literal: true

# This command loops through the contents of STDIN and appends an md5sum
# to the end of the line
require 'digest/md5'

ARGF.each_with_index do |line, _idx|
  puts "#{line.strip},#{Digest::MD5.hexdigest(line.strip)}"
end
