#!/bin/sh
#
# =========================
# ABSTRACT
# =========================
# dump_clean and its SQL query, dump_clean.sql, perform a filtered dump of the measurements table per user request.
#
# The filtering is the same as that used by the iOS app.
#
# This differs from dump_measurements, which does not filter data at all.
# The schema returned is also different; redundant/unused columns have been eliminated, and id/user_id finally included.
# The ORDER BY clause was removed for performance.
#
psql -U safecast --host $POSTGRESQL_ADDRESS safecast -f /var/deploy/api.safecast.org/web_head/current/script/dump_clean.sql
echo "ID,User ID,Captured Time,Latitude,Longitude,Value,Unit,Device ID" | cat - /tmp/mclean.csv > /var/deploy/api.safecast.org/web_head/shared/system/mclean-out.csv
cd /var/deploy/api.safecast.org/web_head/shared/system && tar -czf mclean-out.tar.gz mclean-out.csv
mv mclean-out.tar.gz mclean.tar.gz && mv mclean-out.csv mclean.csv

# rsync to the other server (this only runs on kangaroo)
rsync -Havq --bwlimit 10000 /var/deploy/api.safecast.org/web_head/shared/system/mclean.* horse.api.safecast.org.c66.me:/var/deploy/api.safecast.org/web_head/shared/system/

#
# Now this is available as https://api.safecast.org/system/mclean.tar.gz
#
