#!/bin/sh

# This is alternate query export to be run manually for demos/requests.  Should not be run from cron job.

# NOTES:
# ====================================
# 1. The temp CSV dump imported by SQLite must have 16-bit unsigned integer Z values (in the range 0 - 65535)
# 2. 0 = NODATA.  Do not output a Z value of 0.
# 3. In the iOS app, Z = Z / 1000.0.  (fixed as assumption for Safecast data updates) 
#    Thus if you are not outputting nSv/h <-> uSv/h, scale accordingly by a factor so it works.

rm -f /mnt/tmp/ios13alt.csv

psql -U deploy -h localhost safecastapi -f /data/safecastapi/current/script/ios_query_alt.sql

cd /mnt/tmp
rm -f /mnt/tmp/ios13alt.sqlite
echo -e "PRAGMA journal_mode=OFF;PRAGMA page_size=16384;CREATE TABLE ImpTemp(X VARCHAR(32), Y VARCHAR(32), Z VARCHAR(32));CREATE TABLE Grid1(ID INTEGER PRIMARY KEY, X INT, Y INT, Z INT);\n.separator ','\n.import ios13alt.csv ImpTemp\nINSERT INTO Grid1(X,Y,Z) SELECT CAST(X AS INT), CAST(Y AS INT), CAST(CAST(Z AS INT)-32768 AS INT) FROM ImpTemp;DROP TABLE ImpTemp;VACUUM;" | sqlite3 ios13alt.sqlite
rm -f /data/safecastapi/shared/system/ios13alt.sqlite

mv /mnt/tmp/ios13alt.sqlite /data/safecastapi/shared/system/ios13alt.sqlite
rm -f /mnt/tmp/ios13alt.csv
