#!/bin/sh
psql -U safecast --host $POSTGRESQL_ADDRESS safecast -f /var/deploy/api.safecast.org/web_head/current/script/dump_clean.sql
echo "ID,User ID,Captured Time,Latitude,Longitude,Value,Unit,Device ID" | cat - /tmp/mclean.csv > /var/deploy/api.safecast.org/web_head/shared/system/mclean-out.csv
cd /var/deploy/api.safecast.org/web_head/shared/system && tar -czf mclean-out.tar.gz mclean-out.csv
mv mclean-out.tar.gz mclean.tar.gz && mv mclean-out.csv mclean.csv
#
# Now this is available as https://api.safecast.org/system/mclean.tar.gz
#
