#!/bin/sh
# Add a new City:
# 1. Add the city name to the city_names_array at line 13 of the calculate_radiation_index file
# 2. Add a query with the coordinates to the radiation_index_export.sql file. The file must be named [cityname]_export.csv

psql -U safecast --host $POSTGRESQL_ADDRESS safecast -f /var/deploy/api.safecast.org/web_head/current/script/radiation_index_export.sql
ruby /var/deploy/api.safecast.org/web_head/current/script/calculate_radiation_index
sudo mv /tmp/g20.csv /var/deploy/api.safecast.org/web_head/shared/system
rsync -Havq --bwlimit 10000 /var/deploy/api.safecast.org/web_head/shared/system/g20.* reindeer.api.safecast.org.c66.me:/var/deploy/api.safecast.org/web_head/shared/system/
