#!/usr/bin/env bash

docker-compose up -d postgresql elasticsearch

RETRIES=30
until psql -h localhost -U safecast -d safecast -c "select 1" > /dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
  echo "Waiting for postgres server, $((RETRIES--)) remaining attempts..."
  sleep 1
done

bundle exec rake db:create
bundle exec rake db:schema:load
RAILS_ENV=test bundle exec rake db:schema:load
